using System.Collections.Generic;
using UnityEngine;
using static UnityEngine.EventSystems.RecordingInputModule;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// This segment touch data were generated by Unity Automated QA for the recording from the Assets folder at "Recordings/hatoya.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public static class hatoya_Steps
    {
        public static Dictionary<string, TouchData> Actions = new Dictionary<string, TouchData>();
        static hatoya_Steps()
        {
            Actions.Add("PRESS_Button_(4)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.348169f,
                position =  new Vector3(0.3581489f, 0.4779793f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (4)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.1357143f, -0.1214286f)
            });

            Actions.Add("RELEASE_Button_(4)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.08227921f,
                position =  new Vector3(0.3581489f, 0.4779793f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (4)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.1357143f, -0.1214286f)
            });

            Actions.Add("PRESS_Button_(1)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.7536836f,
                position =  new Vector3(0.3420523f, 0.3471503f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (1)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.02142857f, 0.2285714f)
            });

            Actions.Add("RELEASE_Button_(1)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1824007f,
                position =  new Vector3(0.3420523f, 0.3471503f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (1)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.02142857f, 0.2285714f)
            });

            Actions.Add("PRESS_Button_(2)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.8840065f,
                position =  new Vector3(0.5301811f, 0.3134715f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (2)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.2142857f, 0.04285714f)
            });

            Actions.Add("RELEASE_Button_(2)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1802769f,
                position =  new Vector3(0.5301811f, 0.3134715f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (2)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.2142857f, 0.04285714f)
            });

            Actions.Add("PRESS_Button_(6)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.8879325f,
                position =  new Vector3(0.6599597f, 0.4378238f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (6)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.007142857f, -0.3428572f)
            });

            Actions.Add("RELEASE_Button_(6)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1762462f,
                position =  new Vector3(0.6478873f, 0.4404145f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button (6)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.09285714f, -0.3285714f)
            });

        }
    }
}
