using System.Collections.Generic;
using UnityEngine;
using static UnityEngine.EventSystems.RecordingInputModule;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// This segment touch data were generated by Unity Automated QA for the recording from the Assets folder at "Recordings/hatoya.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public static class hatoya_Steps
    {
        public static Dictionary<string, TouchData> Actions = new Dictionary<string, TouchData>();
        static hatoya_Steps()
        {
            Actions.Add("PRESS_Button_(4)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.769469f,
                position =  new Vector3(0.3382643f, 0.4416445f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (4)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.02857143f, -0.3142857f)
            });

            Actions.Add("RELEASE_Button_(4)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.3292824f,
                position =  new Vector3(0.3382643f, 0.4376658f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (4)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.02857143f, -0.3357143f)
            });

            Actions.Add("PRESS_Button_(1)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.707109f,
                position =  new Vector3(0.3392505f, 0.2771883f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (1)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.02142857f, -0.1285714f)
            });

            Actions.Add("RELEASE_Button_(1)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1302006f,
                position =  new Vector3(0.3402367f, 0.2785146f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (1)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.01428571f, -0.1214286f)
            });

            Actions.Add("PRESS_Button_(2)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.141397f,
                position =  new Vector3(0.4773175f, 0.2811671f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (2)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.1642857f, -0.1071429f)
            });

            Actions.Add("RELEASE_Button_(2)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.167932f,
                position =  new Vector3(0.4773175f, 0.2811671f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (2)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.1642857f, -0.1071429f)
            });

            Actions.Add("PRESS_Button_(6)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.116701f,
                position =  new Vector3(0.6854044f, 0.5092838f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (6)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.2f, 0.05f)
            });

            Actions.Add("RELEASE_Button_(6)", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.04847097f,
                position =  new Vector3(0.6854044f, 0.5092838f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button (6)",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.2f, 0.05f)
            });

        }
    }
}
