using System.Collections.Generic;
using UnityEngine;
using static UnityEngine.EventSystems.RecordingInputModule;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// This segment touch data were generated by Unity Automated QA for the recording from the Assets folder at "Recordings/Keypad2013.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public static class Steps_Keypad2013
    {
        public static Dictionary<string, TouchData> Actions = new Dictionary<string, TouchData>();
        static Steps_Keypad2013()
        {
            Actions.Add("PRESS_Button2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.188335f,
                position =  new Vector3(0.477237f, 0.2862797f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button2",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(-0.2071429f, -0.08571429f)
            });

            Actions.Add("RELEASE_Button2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0f,
                position =  new Vector3(0.477237f, 0.2862797f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button2",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(-0.2071429f, -0.08571429f)
            });

            Actions.Add("PRESS_Button0", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.038429f,
                position =  new Vector3(0.3485086f, 0.1094987f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button0",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(-0.2357143f, 0.02857143f)
            });

            Actions.Add("RELEASE_Button0", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.07372618f,
                position =  new Vector3(0.3485086f, 0.1094987f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button0",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(-0.2357143f, 0.02857143f)
            });

            Actions.Add("PRESS_Button1", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.788064f,
                position =  new Vector3(0.366562f, 0.2308707f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button1",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(-0.07142857f, -0.3857143f)
            });

            Actions.Add("RELEASE_Button1", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.3088059f,
                position =  new Vector3(0.366562f, 0.2308707f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button1",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(-0.07142857f, -0.3857143f)
            });

            Actions.Add("PRESS_Button3", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.888989f,
                position =  new Vector3(0.6593407f, 0.3509235f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button3",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(0.3071429f, 0.2642857f)
            });

            Actions.Add("RELEASE_Button3", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.07388544f,
                position =  new Vector3(0.6593407f, 0.3509235f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button3",
                objectTag = "Untagged",
                objectHierarchy = "KeypadCanvas",
                objectOffset =  new Vector3(0.3071429f, 0.2642857f)
            });

        }
    }
}
