using System.Collections.Generic;
using UnityEngine;
using static UnityEngine.EventSystems.RecordingInputModule;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// This segment touch data were generated by Unity Automated QA for the recording from the Assets folder at "Recordings/hatoya.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public static class Steps_hatoya
    {
        public static Dictionary<string, TouchData> Actions = new Dictionary<string, TouchData>();
        static Steps_hatoya()
        {
            Actions.Add("PRESS_Button_4", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 2.482082f,
                position =  new Vector3(0.3853503f, 0.4642058f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_4",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.1142857f, -0.2285714f)
            });

            Actions.Add("RELEASE_Button_4", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1564293f,
                position =  new Vector3(0.3845541f, 0.4642058f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_4",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.1071429f, -0.2285714f)
            });

            Actions.Add("PRESS_Button_1", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.044722f,
                position =  new Vector3(0.3734076f, 0.3758389f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_1",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.007142857f, 0.2785714f)
            });

            Actions.Add("RELEASE_Button_1", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1550817f,
                position =  new Vector3(0.3734076f, 0.3758389f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_1",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.007142857f, 0.2785714f)
            });

            Actions.Add("PRESS_Button_2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.112646f,
                position =  new Vector3(0.5286624f, 0.2941834f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_2",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.2571429f, -0.2428571f)
            });

            Actions.Add("RELEASE_Button_2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1466317f,
                position =  new Vector3(0.5278662f, 0.2941834f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_2",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.25f, -0.2428571f)
            });

            Actions.Add("PRESS_Button_6", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.152558f,
                position =  new Vector3(0.6210191f, 0.5201342f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_6",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.05714286f, 0.1285714f)
            });

            Actions.Add("RELEASE_Button_6", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1795111f,
                position =  new Vector3(0.6194267f, 0.5190157f),
                positional = false,
                scene = "Keypad",
                waitSignal = "",
                emitSignal = "",
                keyCode = "",
                inputDuration = 0f,
                inputText = "",
                querySelector = "",
                objectName = "Button_6",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.07142857f, 0.1214286f)
            });

        }
    }
}
