using System.Collections;
using System.Linq;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using Unity.CloudTesting;
using UnityEngine.UI;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording from the Assets folder at "/Recordings/hatoya.json".
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public class hatoya_Tests : AutomatedQATestsBase
    {
        /// Generated from recording file: "/Recordings/hatoya.json".
        [CloudTest]
        [UnityTest]
        public IEnumerator CanPlayToEnd()
        {
            yield return PerformAction(hatoya_Steps.Actions["PRESS_Button_(4)"]); // Do a "press" action on "Canvas/Button (4)" in scene "".
            yield return PerformAction(hatoya_Steps.Actions["RELEASE_Button_(4)"]); // Do a "release" action on "Canvas/Button (4)" in scene "".
            yield return PerformAction(hatoya_Steps.Actions["PRESS_Button_(1)"]); // Do a "press" action on "Canvas/Button (1)" in scene "".
            yield return PerformAction(hatoya_Steps.Actions["RELEASE_Button_(1)"]); // Do a "release" action on "Canvas/Button (1)" in scene "".
            yield return PerformAction(hatoya_Steps.Actions["PRESS_Button_(2)"]); // Do a "press" action on "Canvas/Button (2)" in scene "".
            yield return PerformAction(hatoya_Steps.Actions["RELEASE_Button_(2)"]); // Do a "release" action on "Canvas/Button (2)" in scene "".
            yield return PerformAction(hatoya_Steps.Actions["PRESS_Button_(6)"]); // Do a "press" action on "Canvas/Button (6)" in scene "".
            yield return PerformAction(hatoya_Steps.Actions["RELEASE_Button_(6)"]); // Do a "release" action on "Canvas/Button (6)" in scene "".
            yield return PerformAction(EMIT_COMPLETE); // Test complete.

            var historyText = Object.FindObjectsOfType<Text>().FirstOrDefault(x => x.name.Equals("HistoryText"));
            Assert.That(historyText, Is.Not.Null);
            Assert.That(historyText.text, Is.EqualTo("4126"));
        }

        // Steps defined by recording.
        protected override void SetUpTestClass()
        {
            RegisterStep(hatoya_Steps.Actions["PRESS_Button_(4)"]);
            RegisterStep(hatoya_Steps.Actions["RELEASE_Button_(4)"]);
            RegisterStep(hatoya_Steps.Actions["PRESS_Button_(1)"]);
            RegisterStep(hatoya_Steps.Actions["RELEASE_Button_(1)"]);
            RegisterStep(hatoya_Steps.Actions["PRESS_Button_(2)"]);
            RegisterStep(hatoya_Steps.Actions["RELEASE_Button_(2)"]);
            RegisterStep(hatoya_Steps.Actions["PRESS_Button_(6)"]);
            RegisterStep(hatoya_Steps.Actions["RELEASE_Button_(6)"]);
        }

        // Initialize test run data.
        protected override void SetUpTestRun()
        {
            Test.entryScene = "Keypad";
            Test.recordedAspectRatio = new Vector2(0f,0f);
            Test.recordedResolution = new Vector2(0f,0f);
        }
    }
}
