using System.Collections;
using System.Linq;
using NUnit.Framework;
using Unity.RecordedTesting;
using UnityEngine;
using UnityEngine.TestTools;
using UnityEngine.UI;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording: "Recordings/hatoya.json"
    /// You can regenerate this file from the Unity Editor Menu: Tools > Automated QA > Generate Recorded Tests
    /// </summary>
    public class RecordedTest_hatoya : RecordedTestSuiteWithoutScenesInBuild
    {
        /// <summary>
        /// Asserts that the recording can successfully play through to the end. 
        /// </summary>
        [UnityTest]
        [RecordedTest("Recordings/hatoya.json")]
        public IEnumerator CanPlayToEnd()
        {
            yield return RecordedTesting.TestPlayToEnd();

            var historyText = Object.FindObjectsOfType<Text>().FirstOrDefault(x => x.name.Equals("HistoryText"));
            Assert.That(historyText, Is.Not.Null);
            Assert.That(historyText.text, Is.EqualTo("4126"));
        }
    }
}
