using System.Collections;
using System.Linq;
using NUnit.Framework;
using Unity.CloudTesting;
using Unity.RecordedTesting;
using UnityEngine;
using UnityEngine.TestTools;
using UnityEngine.UI;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording: "Recordings/Keypad2013.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    [Category("IgnoreCI")]
    public class SimpleTests_Keypad2013 : RecordedTestSuite
    {
        /// <summary>
        /// Asserts that the recording can successfully play through to the end. 
        /// </summary>
        [UnityTest]
        [CloudTest]
        [RecordedTest("Recordings/Keypad2013.json")]
        public IEnumerator CanPlayToEnd()
        {
            yield return RecordedTesting.TestPlayToEnd();

            // Verify
            var historyText = Object.FindObjectsOfType<Text>().FirstOrDefault(x => x.name.Equals("HistoryText"));
            Assert.That(historyText, Is.Not.Null);
            Assert.That(historyText.text, Is.EqualTo("2013"));
        }
    }
}
