using System.Collections;
using UnityEngine;
using UnityEngine.TestTools;
using Unity.AutomatedQA;
using Unity.CloudTesting;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording from the Assets folder at "/Recordings/hatoya.json".
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public class Tests_hatoya_full_not_use_simplified_driver_code : AutomatedQATestsBase
    {
        /// Generated from recording file: "/Recordings/hatoya.json".
        [UnityTest]
        [CloudTest]
        public IEnumerator CanPlayToEnd()
        {
            yield return Driver.Perform.Action(Steps_hatoya.Actions["PRESS_Button_4"]); // Do a "press" action on "Canvas/Button_4"in scene "Keypad".
            yield return Driver.Perform.Action(Steps_hatoya.Actions["RELEASE_Button_4"]); // Do a "release" action on "Canvas/Button_4"in scene "Keypad".
            yield return Driver.Perform.Action(Steps_hatoya.Actions["PRESS_Button_1"]); // Do a "press" action on "Canvas/Button_1"in scene "Keypad".
            yield return Driver.Perform.Action(Steps_hatoya.Actions["RELEASE_Button_1"]); // Do a "release" action on "Canvas/Button_1"in scene "Keypad".
            yield return Driver.Perform.Action(Steps_hatoya.Actions["PRESS_Button_2"]); // Do a "press" action on "Canvas/Button_2"in scene "Keypad".
            yield return Driver.Perform.Action(Steps_hatoya.Actions["RELEASE_Button_2"]); // Do a "release" action on "Canvas/Button_2"in scene "Keypad".
            yield return Driver.Perform.Action(Steps_hatoya.Actions["PRESS_Button_6"]); // Do a "press" action on "Canvas/Button_6"in scene "Keypad".
            yield return Driver.Perform.Action(Steps_hatoya.Actions["RELEASE_Button_6"]); // Do a "release" action on "Canvas/Button_6"in scene "Keypad".
        }
        // Initialize test run data.
        protected override void SetUpTestRun()
        {
            Test.entryScene = "Keypad";
            Test.recordedAspectRatio = new Vector2(902f,1910f);
            Test.recordedResolution = new Vector2(6016f,3384f);
        }

        // Steps defined by recording.
        protected override void SetUpTestClass()
        {
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["PRESS_Button_4"]);
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["RELEASE_Button_4"]);
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["PRESS_Button_1"]);
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["RELEASE_Button_1"]);
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["PRESS_Button_2"]);
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["RELEASE_Button_2"]);
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["PRESS_Button_6"]);
            Driver.Perform.RegisterStep(Steps_hatoya.Actions["RELEASE_Button_6"]);
        }

    }
}

